### ISSUE TITLE
error on magento 2.4.2 generating category urls

### ISSUE THREAD

**Issue by JannMulton** [olegkoval/magento2-regenerate_url_rewrites#154]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Catalog\Model\ProductRepository::prepareSku() must be of the type string, null given, called in /opt/magento/site/htdocs/vendor/magento/module-catalog/Model/ProductRepository.php on line 794 and defined in /opt/magento/site/htdocs/vendor/magento/module-catalog/Model/ProductRepository.php:804
Stack trace:
#0 /opt/magento/site/htdocs/vendor/magento/module-catalog/Model/ProductRepository.php(794): Magento\Catalog\Model\ProductRepository->prepareSku()
#1 /opt/magento/site/htdocs/vendor/magento/module-catalog/Model/ProductRepository.php(350): Magento\Catalog\Model\ProductRepository->saveProductInLocalCache()
#2 /opt/magento/site/htdocs/vendor/magento/module-catalog/Model/ProductRepository.php(315): Magento\Catalog\Model\ProductRepository->cacheProduct()
#3 /opt/magento/site/htdocs/generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php(32): Magento\Catalog\Model\ProductRepository->getById()
#4 /opt/magento/site/htdocs/vendor/magento/module-catalog-url in /opt/magento/site/htdocs/vendor/magento/module-catalog/Model/ProductRepository.php on line 804

**Comment by olegkoval** [comment]
Reported against Magento 2.4.2, well below the current supported baseline (2.4.7+), with no reproduction details tying it to current code. Closing — please open a new issue with reproduction steps on a supported version if this persists.
